import React from "react";
import { AbsoluteFill, Html5Audio, interpolate, staticFile, useCurrentFrame } from "remotion";
import { linearTiming, TransitionSeries } from "@remotion/transitions";
import { fade } from "@remotion/transitions/fade";
import { Background, clamp } from "./components";
import { Explore } from "./scenes/Explore";
import { Generate } from "./scenes/Generate";
import { Input } from "./scenes/Input";
import { Intro } from "./scenes/Intro";
import { Outro } from "./scenes/Outro";
import { Package } from "./scenes/Package";
import { Verify } from "./scenes/Verify";
import { C, sans } from "./theme";
import { SCENE_START, SCENES, SceneId, TRANSITION } from "./timeline";

const SCENE_COMPONENTS: Record<SceneId, React.FC> = {
  intro: Intro,
  input: Input,
  explore: Explore,
  generate: Generate,
  verify: Verify,
  package: Package,
  outro: Outro,
};

const PIPELINE: { scene: SceneId; label: string; color: string }[] = [
  { scene: "explore", label: "Explore", color: C.exploring },
  { scene: "generate", label: "Generate", color: C.generating },
  { scene: "verify", label: "Verify", color: C.verifying },
  { scene: "package", label: "Package", color: C.completed },
];

/** Persistent 4-step progress bar shown from the input scene through the package scene. */
const PipelineBar: React.FC = () => {
  const frame = useCurrentFrame();
  const shownFrom = SCENE_START.input;
  const shownUntil = SCENE_START.outro + TRANSITION;
  const opacity = interpolate(
    frame,
    [shownFrom, shownFrom + TRANSITION, shownUntil - TRANSITION, shownUntil],
    [0, 1, 1, 0],
    clamp,
  );
  if (opacity === 0) return null;
  // A step becomes active halfway through the cross-fade into its scene.
  const active = PIPELINE.reduce((acc, step, i) => (frame >= SCENE_START[step.scene] + TRANSITION / 2 ? i : acc), -1);

  return (
    <div style={{ position: "absolute", top: 50, left: 0, right: 0, display: "flex", justifyContent: "center", opacity }}>
      <div style={{ display: "flex", alignItems: "center", gap: 18 }}>
        {PIPELINE.map((step, i) => {
          const state = i < active ? "done" : i === active ? "active" : "todo";
          return (
            <React.Fragment key={step.scene}>
              {i > 0 && <div style={{ width: 70, height: 2, background: i <= active ? C.brand : C.border }} />}
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 12,
                  padding: "10px 22px",
                  borderRadius: 999,
                  fontFamily: sans,
                  fontWeight: 600,
                  fontSize: 24,
                  color: state === "todo" ? C.faint : state === "done" ? C.brand : step.color,
                  background: state === "active" ? `${step.color}22` : "transparent",
                  border: `1px solid ${state === "active" ? step.color : state === "done" ? `${C.brand}66` : C.border}`,
                }}
              >
                <span>{state === "done" ? "✓" : `0${i + 1}`}</span>
                {step.label}
              </div>
            </React.Fragment>
          );
        })}
      </div>
    </div>
  );
};

export const PickleScoutIntro: React.FC = () => (
  <AbsoluteFill>
    <Background />
    {/* Generated by scripts/make-music.py; arrangement follows timeline.ts. */}
    <Html5Audio src={staticFile("music.wav")} />
    <TransitionSeries>
      {SCENES.flatMap((scene, i) => {
        const Scene = SCENE_COMPONENTS[scene.id];
        const seq = (
          <TransitionSeries.Sequence key={scene.id} durationInFrames={scene.duration}>
            <Scene />
          </TransitionSeries.Sequence>
        );
        return i === 0
          ? [seq]
          : [
              <TransitionSeries.Transition
                key={`${scene.id}-fade`}
                presentation={fade()}
                timing={linearTiming({ durationInFrames: TRANSITION })}
              />,
              seq,
            ];
      })}
    </TransitionSeries>
    <PipelineBar />
  </AbsoluteFill>
);
